packages:
  - packages/*
allowBuilds:
  ' ': true
  /: true
  '@': true
  a: true
  b: true
  e: true
  f: true
  g: true
  i: true
  j: true
  l: true
  n: true
  o: true
  p: true
  r: true
  s: true
  t: true
  u: true
