import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

/* ─────────────────────────── validators ─────────────────────────── */

const LAUNCHER_SESSION_RE = /^(?:fh-agent|sf-team)-[A-Za-z0-9_-]{1,64}$/;
const TMUX_SESSION_RE = /^[A-Za-z0-9._\-]{1,64}$/;
const LOG_PATH_RE = /^[A-Za-z0-9/_.\-]+$/;
const RUN_ID_RE = /^[A-Za-z0-9_-]{1,64}$/;
const TMUX_WINDOW_ID_RE = /^@\d+$/;
/**
 * Tool-derived session alias: `<toolName>-<N>`. Matches what the
 * orchestrator computes from the running tool (e.g. sf_team_auto-1).
 * This is what the user sees in `tmux ls` after the orchestrator
 * renames the launcher's `fh-agent-<hex>` session.
 *
 * Lowercase by convention — every tool entry point uses a lowercase
 * snake_case name, so we reject mixed-case inputs early instead of
 * silently rendering an inconsistent session name.
 */
const TOOL_ALIAS_RE = /^[a-z][a-z0-9_-]{1,62}-\d{1,3}$/;

/** Absolute path to the pretty-pane.mjs filter shipped with this package. */
const PRETTY_PANE_PATH = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "scripts",
  "pretty-pane.mjs",
);

/**
 * tmux user-option key used as an IDENTITY-SPECIFIC ownership marker
 * on every session we successfully prepare. The value is the ORIGINAL
 * launcher session name (e.g. `fh-agent-deadbeef`) supplied to
 * `prepareSession`. Adoption requires an exact match against the
 * caller's `args.sessionName`, so:
 *
 *  - A user-owned session that happens to share our alias name has no
 *    marker → no adoption.
 *  - A different fh-agent launcher (different `fh-agent-<hex>`)
 *    that happens to share our alias name has a marker, but with a
 *    different identity → no adoption.
 *  - Only a session that WE (this same logical launcher chain) prepared
 *    and stamped will match → adoption is safe.
 *
 * Launcher-session hex is randomly generated by `scripts/fh-agent`
 * (~4 billion possibilities) so concurrent launcher collisions are
 * effectively impossible.
 *
 * The OPTION KEY itself stays under the historical `@sf-team-`
 * namespace so existing tmux sessions stamped before the launcher
 * was renamed are still recognized; only the launcher SESSION NAME
 * (the value stored under this key) changed when we rebranded.
 */
const OWNER_OPTION = "@sf-team-owner-of";

/**
 * Strict launcher-emitted session name: matches what `scripts/fh-agent`
 * generates and what arrives via `FH_AGENT_TMUX_SESSION`. Anything that
 * does not match is regenerated/rejected.
 */
export function isValidLauncherSessionName(s: string): boolean {
  return LAUNCHER_SESSION_RE.test(s);
}

/**
 * Permissive tmux-session name: matches tmux's own session-name rules.
 * Used ONLY when falling back to `tmux display-message -p '#S'` to
 * accept a user's existing session (e.g. `work` or `0`).
 */
export function isValidTmuxSessionName(s: string): boolean {
  return TMUX_SESSION_RE.test(s);
}

/**
 * Log path validator. Rejects spaces, quotes, semicolons, and any
 * shell-special character because the path is interpolated into a
 * tmux `split-window` command which IS shell-interpreted by tmux's
 * own session.
 */
export function isValidLogPath(p: string): boolean {
  return LOG_PATH_RE.test(p);
}

export class InvalidSessionNameError extends Error {
  constructor(s: string) {
    super(`Invalid tmux session name (failed both launcher-strict and tmux-permissive validators): ${JSON.stringify(s)}`);
    this.name = "InvalidSessionNameError";
  }
}

/* ─────────────────────────── runner abstraction ─────────────────────────── */

export interface RunResult {
  code: number;
  stdout: string;
  stderr: string;
}

export interface TmuxRunner {
  run(args: string[]): RunResult;
}

class RealTmuxRunner implements TmuxRunner {
  run(args: string[]): RunResult {
    // argv form, no shell. The pane's `tail -F <path>` command argument
    // IS shell-interpreted by tmux's split-window itself; the path
    // validator (isValidLogPath) is the defense for that.
    const r = spawnSync("tmux", args, { shell: false, encoding: "utf8" });
    return {
      code: r.status ?? 1,
      stdout: (r.stdout as string | null) ?? "",
      stderr: (r.stderr as string | null) ?? "",
    };
  }
}

const DEFAULT_RUNNER: TmuxRunner = new RealTmuxRunner();

/* ─────────────────────────── session detection ─────────────────────────── */

export interface ActiveSession {
  sessionName: string;
  /**
   * `true` when the session was launched by `scripts/fh-agent` (the
   * `FH_AGENT_TMUX_SESSION` env path); `false` when we fell back to
   * the user's existing tmux session via `display-message`.
   */
  isLauncherSession: boolean;
}

export interface DetectOpts {
  /** Mockable env (defaults to `process.env`). */
  env?: NodeJS.ProcessEnv;
  /** Injectable tmux runner. Defaults to a real `spawnSync` wrapper. */
  runner?: TmuxRunner;
}

export function getActiveSession(opts: DetectOpts = {}): ActiveSession | null {
  const env = opts.env ?? process.env;
  if (!env.TMUX) return null;
  const runner = opts.runner ?? DEFAULT_RUNNER;

  // Always read the current tmux session so we can validate the env
  // var against it. `display-message -p '#S'` is the canonical source
  // of truth for "what session is this terminal attached to right
  // now"; the env var is just a hint that may be stale.
  const dm = runner.run(["display-message", "-p", "#S"]);
  const currentName = dm.code === 0
    ? (dm.stdout.endsWith("\n") ? dm.stdout.slice(0, -1) : dm.stdout)
    : "";
  const validCurrent = currentName && isValidTmuxSessionName(currentName) ? currentName : "";

  // 1. Strict launcher-session env var path. Trust requires
  //    continuity with the CURRENT tmux session: either the env name
  //    matches `#S` (fresh launcher; not yet renamed), or the current
  //    session carries our identity marker pointing back at the env
  //    name (we previously renamed launcher→alias and are now in a
  //    follow-up call from the same logical chain). Without this
  //    check, a process that inherits a stale `FH_AGENT_TMUX_SESSION`
  //    from an unrelated parent could be silently treated as that
  //    other launcher.
  //
  //    Critical: when `fromEnv` is set but the current session is
  //    demonstrably NOT ours (env != #S AND marker absent / different
  //    identity), we MUST treat the current session as a user
  //    session — not consult the relaxed env-missing fallbacks
  //    below. We have an identity to protect; the no-hijack guarantee
  //    requires refusing to claim a session that another launcher
  //    has stamped (different marker value) or that the user owns
  //    (no marker).
  const fromEnv = env.SF_TEAM_TMUX_SESSION ?? env.FH_AGENT_TMUX_SESSION;
  if (fromEnv && isValidLauncherSessionName(fromEnv)) {
    if (validCurrent && fromEnv === validCurrent) {
      return { sessionName: fromEnv, isLauncherSession: true };
    }
    if (validCurrent) {
      const owner = runner.run(["show-option", "-t", validCurrent, "-qv", OWNER_OPTION]);
      const ownerVal = owner.code === 0 ? owner.stdout.trim() : "";
      if (ownerVal === fromEnv) {
        return { sessionName: fromEnv, isLauncherSession: true };
      }
    }
    // Env identity is set but the current session isn't ours. Treat
    // as a user session. (Without this early-return, the relaxed
    // env-missing fallbacks below would weaken the no-hijack
    // guarantee.)
    if (!validCurrent) return null;
    return { sessionName: validCurrent, isLauncherSession: false };
  }

  // 2. Permissive fallback: trust the current tmux session name.
  if (!validCurrent) return null;

  // 2a. Env-var-lost fallback. `scripts/fh-agent` exports
  //     FH_AGENT_TMUX_SESSION before re-execing into tmux, but
  //     child-process chains (shell wrappers, IDE-integrated
  //     terminals, language-server hosts) can strip that var while
  //     the underlying tmux session it created persists. With no env
  //     value to compare against, we have no identity to protect —
  //     the no-hijack concern that scopes path #1 does not apply
  //     here, so we can use relaxed signals on the CURRENT session
  //     to recover launcher status:
  //
  //       a) Name strictly matches the launcher pattern
  //          (`fh-agent-<hex>`). Only `scripts/fh-agent` generates
  //          this name; users do not create sessions with this exact
  //          shape.
  //       b) Current session carries our identity marker
  //          (`@sf-team-owner-of`), meaning a prior
  //          `prepareSession` call from THIS codebase stamped it.
  //          Marker presence alone is sufficient because ONLY this
  //          codebase ever writes that user-option key.
  //
  //     Either is enough.
  if (isValidLauncherSessionName(validCurrent)) {
    return { sessionName: validCurrent, isLauncherSession: true };
  }
  const fallbackOwner = runner.run(["show-option", "-t", validCurrent, "-qv", OWNER_OPTION]);
  if (fallbackOwner.code === 0 && fallbackOwner.stdout.trim().length > 0) {
    return { sessionName: validCurrent, isLauncherSession: true };
  }

  return { sessionName: validCurrent, isLauncherSession: false };
}

export function inTmux(opts: DetectOpts = {}): boolean {
  return getActiveSession(opts) !== null;
}

/* ─────────────────────────── per-run log directory ─────────────────────────── */

/**
 * Sanitize a runId by stripping any character outside `[A-Za-z0-9_-]`.
 * UUIDs are kept verbatim (their dashes are valid). Used to defend
 * against a malformed/maliciously-set runId reaching the on-disk path.
 */
function sanitizeRunId(runId: string): string {
  return runId.replace(/[^A-Za-z0-9_-]/g, "");
}

export interface EnsureLogDirOpts {
  /** Override for tests. Defaults to `os.tmpdir()`. */
  tmpDir?: string;
}

export function ensureLogDir(sessionName: string, runId: string, opts: EnsureLogDirOpts = {}): string {
  if (!isValidLauncherSessionName(sessionName) && !isValidTmuxSessionName(sessionName)) {
    throw new InvalidSessionNameError(sessionName);
  }
  const safeRunId = sanitizeRunId(runId);
  if (!RUN_ID_RE.test(safeRunId)) {
    throw new Error(`Invalid runId after sanitization: ${JSON.stringify(runId)} → ${JSON.stringify(safeRunId)}`);
  }
  const hash = createHash("sha1")
    .update(`${sessionName}:${runId}`)
    .digest("hex")
    .slice(0, 8);
  const dirname = `sf-team-${hash}-${safeRunId}`;
  const tmpDir = opts.tmpDir ?? os.tmpdir();
  const full = path.join(tmpDir, dirname);
  mkdirSync(full, { recursive: true });
  return full;
}

/* ─────────────────────────── pane title sanitization ─────────────────────────── */

const PANE_TITLE_CONTROL_RE = /[\x00-\x1F\x7F]/g;
const PANE_TITLE_MAX = 80;

export function sanitizePaneTitle(raw: string): string {
  return raw.replace(PANE_TITLE_CONTROL_RE, "").slice(0, PANE_TITLE_MAX);
}

/* ─────────────────────────── pane lifecycle ─────────────────────────── */

export interface ManagerOpts {
  runner?: TmuxRunner;
}

export type PaneLayoutRole = "milestone" | "story" | "reviewer" | "standalone";

export interface OpenAgentPaneArgs {
  sessionName: string;
  agentId: string;
  paneTitle: string;
  /**
   * Pre-computed absolute log path. Mutually exclusive with `runId`.
   * Caller-owned. Validated against `isValidLogPath`.
   */
  logPath?: string;
  /**
   * Per-orchestrator-run identifier. When set (and `logPath` is omitted),
   * the manager OWNS the log directory: it generates the per-agent log
   * path as `<ensureLogDir(sessionName, runId)>/<sanitizedAgentId>.log`,
   * creates the directory on first call, and returns the resolved path
   * to the caller. Recommended for normal use.
   */
  runId?: string;
  /**
   * When true (default), the pane runs the streamed log through the
   * `pretty-pane.mjs` filter so the user sees human-readable lines
   * instead of raw JSON-protocol events. Set to false to fall back to
   * a plain `tail -F` (mostly for tests and very small log paths).
   */
  pretty?: boolean;
  /** Group id for strategy-aware tmux layouts, usually a milestone id such as `M1`. */
  groupId?: string;
  /** Parent group id for story/reviewer panes that belong to a milestone lane. */
  parentGroupId?: string;
  /** Layout role. Omitted preserves the original right-column stacking behavior. */
  layoutRole?: PaneLayoutRole;
  /** Optional story id used by higher-level callers for diagnostics/title composition. */
  storyId?: string;
  /** Optional group title retained for future tmux display improvements. */
  groupTitle?: string;
}

export interface PrepareSessionArgs {
  /** Current launcher-emitted session name (e.g. `fh-agent-deadbeef`). */
  sessionName: string;
  /**
   * Tool-derived alias to rename the session to. Format
   * `<toolName>-<N>` (e.g. `sf_team_auto-1`). When the alias already
   * matches the strict regex AND no other session exists with that
   * alias, tmux's `rename-session` succeeds and the user sees the new
   * name everywhere. The orchestrator computes the alias and `N`.
   */
  sessionAlias: string;
}

export interface PrepareSessionResult {
  /** The (possibly renamed) session name now in use. */
  sessionName: string;
  /** tmux pane id of the user's main interactive shell (titled `Main`). */
  mainPaneId: string;
  /** tmux window id (e.g. `@7`) of the active window. */
  windowId: string;
}

export class TmuxManager {
  private readonly runner: TmuxRunner;
  private readonly panes = new Map<string, { paneId: string; agentId: string; groupId?: string; layoutRole?: PaneLayoutRole }>(); // paneId -> meta
  private readonly paneGroups = new Map<string, { anchorPaneId: string; lastPaneId: string }>();
  private readonly mainPaneBySession = new Map<string, string>();
  /**
   * tmux pane id of the most recently opened agent pane. New agent
   * panes split THIS pane vertically so the right column stacks
   * `agent-1` on top, `agent-2` below it, etc. When the most recent
   * pane closes, the column reflows naturally without a leftover
   * empty container pane.
   */
  private lastAgentPaneId: string | undefined;
  private logDirCache: { sessionName: string; runId: string; dir: string } | undefined;

  constructor(opts: ManagerOpts = {}) {
    this.runner = opts.runner ?? DEFAULT_RUNNER;
  }

  /**
   * Read the identity-specific ownership marker from the named
   * session. Returns the marker VALUE (the original launcher session
   * name as stamped by a prior `prepareSession`) or `undefined` when
   * the marker is absent / unreadable. The caller compares this
   * against its own `args.sessionName` to decide ownership — we don't
   * do the comparison here so the call sites are explicit about the
   * identity they expect.
   *
   * `show-option -qv` returns the value only and exits 0 with empty
   * stdout when the option is unset (so we never throw on a missing
   * marker, which is the common "not ours" case).
   */
  private readOwnerMarker(sessionName: string): string | undefined {
    const r = this.runner.run(["show-option", "-t", sessionName, "-qv", OWNER_OPTION]);
    if (r.code !== 0) return undefined;
    const v = r.stdout.trim();
    return v.length > 0 ? v : undefined;
  }

  /**
   * Resolve the per-run log directory for `(sessionName, runId)`.
   * Cached so the directory is created at most once per manager
   * instance. Callers that pass a precomputed `logPath` to
   * `openAgentPane` can ignore this method.
   */
  private resolveAgentLogPath(sessionName: string, runId: string, agentId: string): string {
    const key = `${sessionName}:${runId}`;
    if (!this.logDirCache || `${this.logDirCache.sessionName}:${this.logDirCache.runId}` !== key) {
      this.logDirCache = { sessionName, runId, dir: ensureLogDir(sessionName, runId) };
    }
    const safeAgentId = agentId.replace(/[^A-Za-z0-9_-]/g, "_") || "agent";
    return path.join(this.logDirCache.dir, `${safeAgentId}.log`);
  }

  private themeForPrettyPane(): "codex" | "plain" {
    // Strict allowlist: the returned value is interpolated into the tmux
    // shell command as an env assignment, so do not widen without quoting.
    const raw = (process.env.SF_TEAM_PANE_THEME || process.env.PRETTY_PANE_THEME || "codex").trim().toLowerCase();
    return raw === "plain" ? "plain" : "codex";
  }

  private splitArgsForPane(args: OpenAgentPaneArgs): string[] {
    const role = args.layoutRole;
    const splitArgs: string[] = ["split-window"];
    if (!role || role === "standalone") {
      if (this.lastAgentPaneId === undefined) splitArgs.push("-h", "-t", args.sessionName);
      else splitArgs.push("-v", "-t", this.lastAgentPaneId);
      return splitArgs;
    }

    if (role === "story") {
      const parentGroupId = args.parentGroupId ?? args.groupId;
      const group = parentGroupId ? this.paneGroups.get(parentGroupId) : undefined;
      if (group) splitArgs.push("-v", "-t", group.lastPaneId);
      else splitArgs.push("-h", "-t", args.sessionName);
      return splitArgs;
    }

    // Milestone and reviewer lanes are horizontal siblings anchored to the
    // prepared main pane when available. Falling back to the session name
    // preserves behavior for user-owned sessions that were not decorated.
    splitArgs.push("-h", "-t", this.mainPaneBySession.get(args.sessionName) ?? args.sessionName);
    return splitArgs;
  }

  private recordPaneGroup(paneId: string, args: OpenAgentPaneArgs): void {
    const role = args.layoutRole;
    if (!role || role === "standalone") {
      this.lastAgentPaneId = paneId;
      return;
    }
    const groupId = role === "story" ? (args.parentGroupId ?? args.groupId) : args.groupId;
    if (!groupId) return;
    const existing = this.paneGroups.get(groupId);
    if (!existing || role === "milestone" || role === "reviewer") {
      // Milestone/reviewer lanes are lane roots. Reopening the same group
      // intentionally replaces the root with the most recent pane.
      this.paneGroups.set(groupId, { anchorPaneId: paneId, lastPaneId: paneId });
      return;
    }
    this.paneGroups.set(groupId, { ...existing, lastPaneId: paneId });
  }

  private recomputeGroup(groupId: string): void {
    const survivors = [...this.panes.values()].filter((p) => p.groupId === groupId);
    if (survivors.length === 0) {
      this.paneGroups.delete(groupId);
      return;
    }
    this.paneGroups.set(groupId, {
      anchorPaneId: survivors[0].paneId,
      lastPaneId: survivors[survivors.length - 1].paneId,
    });
  }

  private recomputeLastUngroupedPane(): void {
    const survivors = [...this.panes.values()].filter((p) => !p.groupId);
    this.lastAgentPaneId = survivors.length > 0 ? survivors[survivors.length - 1].paneId : undefined;
  }

  /**
   * One-shot session decoration: rename the launcher's `fh-agent-<hex>`
   * session to a tool-derived alias (`<toolName>-<N>`), title the
   * existing main pane `Main`, and enable `pane-border-status top` so
   * the user sees pane titles in tmux's borders.
   *
   * Idempotent: when the alias already matches `sessionName`, only the
   * border-status / main-pane-title steps run.
   *
   * Returns the (possibly renamed) session name + the main pane id +
   * the active window id. The caller passes the returned `sessionName`
   * to subsequent `openAgentPane` calls.
   */
  prepareSession(args: PrepareSessionArgs): PrepareSessionResult {
    if (!isValidLauncherSessionName(args.sessionName) && !isValidTmuxSessionName(args.sessionName)) {
      throw new InvalidSessionNameError(args.sessionName);
    }
    if (!TOOL_ALIAS_RE.test(args.sessionAlias)) {
      throw new Error(`Invalid session alias (must match ^[a-z][a-z0-9_-]+-\\d+$): ${JSON.stringify(args.sessionAlias)}`);
    }

    let sessionName = args.sessionName;

    if (args.sessionAlias !== sessionName) {
      const aliasExists = this.runner.run(["has-session", "-t", args.sessionAlias]);
      if (aliasExists.code === 0) {
        // The alias session already exists. Possible causes:
        //   1. A prior `prepareSession` from this same logical
        //      launcher chain renamed `fh-agent-<hex>` → alias.
        //   2. The user has an unrelated session named `<alias>`.
        //   3. A DIFFERENT sf-team launcher (different
        //      `fh-agent-<hex>`) renamed its session to this same
        //      alias name (e.g. via a stale `nextSessionAlias` race).
        //
        // The IDENTITY-specific marker handles all three: we adopt
        // only when the marker on the alias session equals OUR
        // `args.sessionName` (the original launcher session name).
        // Case 1 → match → adopt. Case 2 → marker absent → don't
        // adopt. Case 3 → marker present but value is the OTHER
        // launcher's session name → don't adopt.
        const marker = this.readOwnerMarker(args.sessionAlias);
        if (marker !== undefined && marker === args.sessionName) {
          sessionName = args.sessionAlias;
        }
      } else {
        const rename = this.runner.run(["rename-session", "-t", sessionName, args.sessionAlias]);
        if (rename.code === 0) {
          sessionName = args.sessionAlias;
        }
        // If rename failed (race / version-specific), we keep the
        // original. Subsequent calls validate against the original.
      }
    }

    return this.decorateSessionCore({ sessionName, ownerMarkerSessionName: args.sessionName, sessionAlias: args.sessionAlias });
  }

  /**
   * One-shot visual decoration for any tmux session where an sf_team_* tool is
   * running. Unlike prepareSession, this never renames or claims ownership of
   * the session; it only titles the main pane and enables sticky pane headers.
   */
  decorateSession(args: { sessionName: string }): PrepareSessionResult {
    if (!isValidLauncherSessionName(args.sessionName) && !isValidTmuxSessionName(args.sessionName)) {
      throw new InvalidSessionNameError(args.sessionName);
    }
    return this.decorateSessionCore({ sessionName: args.sessionName });
  }

  private decorateSessionCore(args: { sessionName: string; ownerMarkerSessionName?: string; sessionAlias?: string }): PrepareSessionResult {
    const { sessionName } = args;

    if (args.ownerMarkerSessionName !== undefined) {
      // Stamp our identity-specific ownership marker. The value is the
      // ORIGINAL launcher session name as supplied by the caller, so a
      // follow-up `prepareSession` from the SAME logical launcher chain
      // (which sees the same stale `args.sessionName` from
      // FH_AGENT_TMUX_SESSION) recognizes ownership. A different
      // launcher (different `fh-agent-<hex>`) cannot match.
      // Idempotent: re-setting the same value is a no-op.
      this.runner.run(["set-option", "-t", sessionName, OWNER_OPTION, args.ownerMarkerSessionName]);
    }

    // Resolve the active window id under the target session.
    const winIdRes = this.runner.run(["display-message", "-t", sessionName, "-p", "#{window_id}"]);
    if (winIdRes.code !== 0) {
      throw new Error(`tmux display-message failed: ${winIdRes.stderr.trim() || `code=${winIdRes.code}`}`);
    }
    const windowId = winIdRes.stdout.trim();
    if (!TMUX_WINDOW_ID_RE.test(windowId)) {
      throw new Error(`Unexpected window id from tmux: ${JSON.stringify(windowId)}`);
    }

    if (args.sessionAlias !== undefined) {
      // Rename the active window to match the session alias so tmux's
      // status bar shows `<alias>:<alias>`. Best-effort; older tmux
      // versions may behave slightly differently.
      this.runner.run(["rename-window", "-t", windowId, args.sessionAlias]);
    }

    // Identify the main pane: the first pane in the active window
    // BEFORE we open any agent pane. List panes, take the one with
    // pane_index=0 (or, defensively, the first pane in the list).
    const listRes = this.runner.run(["list-panes", "-t", windowId, "-F", "#{pane_id} #{pane_index}"]);
    if (listRes.code !== 0) {
      throw new Error(`tmux list-panes failed: ${listRes.stderr.trim() || `code=${listRes.code}`}`);
    }
    let mainPaneId: string | undefined;
    for (const line of listRes.stdout.split("\n")) {
      const m = line.match(/^(%\d+)\s+(\d+)$/);
      if (m && m[2] === "0") {
        mainPaneId = m[1];
        break;
      }
    }
    if (!mainPaneId) {
      // Fallback: take the first pane in the list.
      const m = listRes.stdout.split("\n")[0].match(/^(%\d+)/);
      if (!m) throw new Error(`tmux list-panes returned no panes: ${JSON.stringify(listRes.stdout)}`);
      mainPaneId = m[1];
    }

    // Title the main pane. Best-effort.
    this.runner.run(["select-pane", "-t", mainPaneId, "-T", "Main"]);
    this.mainPaneBySession.set(sessionName, mainPaneId);

    // Enable pane-border-status so the user sees the pane titles. We
    // set both the status position and the format. Best-effort —
    // tmux <2.3 doesn't support pane-border-status; we ignore the
    // failure and the panes still work, just without titled borders.
    this.runner.run(["set-option", "-t", sessionName, "pane-border-status", "top"]);
    this.runner.run([
      "set-option",
      "-t",
      sessionName,
      "pane-border-format",
      "[#{pane_title}]",
    ]);

    return { sessionName, mainPaneId, windowId };
  }

  /**
   * Compute the next-available tool-derived alias by enumerating
   * existing tmux sessions matching `<toolName>-N` and returning the
   * smallest unused N (>= 1). Returns `<toolName>-<N>`.
   *
   * Use the optional `runner` arg to override the default.
   */
  nextSessionAlias(toolName: string): string {
    if (!/^[a-z][a-z0-9_-]{0,62}$/.test(toolName)) {
      throw new Error(`Invalid toolName (must be lowercase snake/kebab starting with a letter): ${JSON.stringify(toolName)}`);
    }
    const list = this.runner.run(["list-sessions", "-F", "#{session_name}"]);
    const used = new Set<number>();
    if (list.code === 0) {
      const re = new RegExp(`^${toolName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}-(\\d+)$`);
      for (const line of list.stdout.split("\n")) {
        const m = line.match(re);
        if (m) used.add(Number(m[1]));
      }
    }
    let n = 1;
    while (used.has(n)) n += 1;
    return `${toolName}-${n}`;
  }

  /**
   * Open a per-agent pane that tails the agent's raw stdout/stderr log
   * through the pretty-pane filter (so the user sees human-readable
   * tool calls + streamed text instead of JSON-protocol noise).
   *
   * Layout:
   *   - First openAgentPane in the session splits the active window
   *     HORIZONTALLY (the active window has a single main pane on
   *     the left; the new agent pane appears as the right column).
   *   - Subsequent openAgentPane calls split the previous agent pane
   *     VERTICALLY (so agent panes stack below each other in the
   *     right column).
   *   - When the most recent agent pane closes, the column reflows
   *     naturally — there is NO empty container pane left behind.
   *
   * Either `logPath` (caller-owned) OR `runId` (manager-owned) must be
   * supplied. With `runId`, the manager creates and caches a per-run
   * log directory on first call and derives `<dir>/<agentId>.log`.
   */
  openAgentPane(args: OpenAgentPaneArgs): { paneId: string; logPath: string } {
    if (!isValidLauncherSessionName(args.sessionName) && !isValidTmuxSessionName(args.sessionName)) {
      throw new InvalidSessionNameError(args.sessionName);
    }
    let logPath: string;
    if (args.logPath !== undefined && args.runId !== undefined) {
      throw new Error("openAgentPane: pass exactly one of `logPath` or `runId` (not both).");
    } else if (args.logPath !== undefined) {
      logPath = args.logPath;
    } else if (args.runId !== undefined) {
      logPath = this.resolveAgentLogPath(args.sessionName, args.runId, args.agentId);
    } else {
      throw new Error("openAgentPane: one of `logPath` or `runId` is required.");
    }
    if (!isValidLogPath(logPath)) {
      throw new Error(`Invalid log path (rejected by isValidLogPath): ${JSON.stringify(logPath)}`);
    }
    if (!isValidLogPath(PRETTY_PANE_PATH)) {
      // Defensive: the bundled pretty-pane path is fixed at install
      // time, but if a user installs the package into an exotic prefix
      // with shell-special characters, fall back to plain tail.
    }

    // Build the pane's command. With `pretty=true` (default) we run
    // `tail -F <log> | node <pretty-pane>`. With `pretty=false`, plain
    // `tail -F <log>`. The command is shell-interpreted by tmux's
    // split-window — both `logPath` and `PRETTY_PANE_PATH` are
    // validated paths (no shell-special chars).
    const usePretty = args.pretty !== false && isValidLogPath(PRETTY_PANE_PATH);
    const paneCmd = usePretty
      ? `tail -F ${logPath} | PRETTY_PANE_THEME=${this.themeForPrettyPane()} node ${PRETTY_PANE_PATH}`
      : `tail -F ${logPath}`;

    // Decide split target. No group metadata preserves the original
    // right-column stacking behavior; group metadata creates milestone
    // horizontal lanes and story panes stacked vertically inside them.
    const splitArgs = this.splitArgsForPane(args);
    splitArgs.push("-P", "-F", "#{pane_id}", paneCmd);

    const splitRes = this.runner.run(splitArgs);
    if (splitRes.code !== 0) {
      throw new Error(`tmux split-window (agent pane) failed: ${splitRes.stderr.trim() || `code=${splitRes.code}`}`);
    }
    const paneId = splitRes.stdout.trim();
    if (!/^%\d+$/.test(paneId)) {
      throw new Error(`Unexpected pane id from tmux split-window: ${JSON.stringify(paneId)}`);
    }
    const titleRes = this.runner.run([
      "select-pane",
      "-t",
      paneId,
      "-T",
      sanitizePaneTitle(args.paneTitle),
    ]);
    if (titleRes.code !== 0) {
      throw new Error(
        `tmux select-pane (set agent-pane title) failed: ${titleRes.stderr.trim() || `code=${titleRes.code}`}`,
      );
    }
    const paneGroupId = args.layoutRole && args.layoutRole !== "standalone"
      ? (args.layoutRole === "story" ? (args.parentGroupId ?? args.groupId) : args.groupId)
      : undefined;
    this.panes.set(paneId, { paneId, agentId: args.agentId, groupId: paneGroupId, layoutRole: args.layoutRole });
    this.recordPaneGroup(paneId, args);
    return { paneId, logPath };
  }

  /**
   * Kill a pane previously opened by `openAgentPane`. Accepts either
   * the tmux pane id (e.g. `%9`) — preferred per the M5 contract — or
   * an agentId for callers that prefer to track by their own key.
   * Idempotent: "can't find pane" / "no such pane" stderr is swallowed
   * because the pane may have closed concurrently (e.g. user closed it
   * manually).
   */
  closeAgentPane(paneIdOrAgentId: string): void {
    let paneId: string | undefined;
    if (this.panes.has(paneIdOrAgentId)) {
      paneId = paneIdOrAgentId;
    } else {
      // Lookup by agentId.
      for (const [id, meta] of this.panes) {
        if (meta.agentId === paneIdOrAgentId) {
          paneId = id;
          break;
        }
      }
    }
    if (!paneId) return;
    const meta = this.panes.get(paneId);
    const r = this.runner.run(["kill-pane", "-t", paneId]);
    this.panes.delete(paneId);
    // If we just closed the most recently opened pane, reset the
    // tracker so the NEXT openAgentPane creates a fresh right column
    // by splitting the active window. Otherwise the next pane would
    // try to split a now-dead pane id.
    if (meta?.groupId) this.recomputeGroup(meta.groupId);
    if (!meta?.groupId && this.lastAgentPaneId === paneId) this.recomputeLastUngroupedPane();
    if (r.code === 0) return;
    if (/can't find pane|no such pane/i.test(r.stderr)) return;
    throw new Error(`tmux kill-pane failed for ${paneIdOrAgentId} (${paneId}): ${r.stderr.trim() || `code=${r.code}`}`);
  }

  /**
   * Close every pane this manager opened. Best-effort; errors swallowed
   * so one bad pane does not prevent the rest from closing.
   *
   * The `sessionName` argument is accepted to match the M5 acceptance
   * criterion API contract; it is informational/validation-only — the
   * manager closes only panes it created (tracked in its private Map),
   * not arbitrary panes in the named session.
   */
  closeAllPanes(sessionName?: string): void {
    if (sessionName !== undefined) {
      // Defensive validation: reject malformed names so a caller can't
      // smuggle injection through closeAllPanes.
      if (!isValidLauncherSessionName(sessionName) && !isValidTmuxSessionName(sessionName)) {
        throw new InvalidSessionNameError(sessionName);
      }
    }
    for (const paneId of [...this.panes.keys()]) {
      try {
        this.closeAgentPane(paneId);
      } catch {
        // Swallow; teardown must continue.
      }
    }
    this.panes.clear();
    this.paneGroups.clear();
    this.lastAgentPaneId = undefined;
  }

  /** Test/inspection accessor: pane ids currently tracked. */
  trackedPaneIds(): string[] {
    return [...this.panes.keys()];
  }

  /** Test/inspection accessor: agent ids currently tracked. */
  trackedAgentIds(): string[] {
    return [...this.panes.values()].map((m) => m.agentId);
  }
}
